name: actions

on:
  push:
    branches: [ "main" ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      - name: Build with Gradle
        run: ./gradlew clean build -x test

      # Upload JAR as GitHub Artifact
#      - name: Upload JAR as Artifact
#        uses: actions/upload-artifact@v4
#        with:
#          name: spring-boot-app
#          path: build/libs/*.jar
#          overwrite: true
#          if-no-files-found: error
#
#      # Publish to GitHub Packages
#      - name: Publish package
#        run: ./gradlew publish
#        env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#          GITHUB_ACTOR: ${{ github.actor }}

      - name: Log in to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Build & Push Docker Image
      - name: Build and Push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ghcr.io/${{ github.repository }}/springboot-app:latest
